config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'welcome#index'
  post 'newsletter_subscribe', to: 'welcome#newsletter_subscribe'

  resources :contact, only: [:new, :create]
  resources :posts, only: [:index, :show]
  resources :properties, only: [:show] do
    get :highlighted, on: :collection
    get :reference_search, on: :collection
    get :images, on: :member
    post :consult, on: :member
    post :consult_express, on: :member
  end

  get "/propiedades/:property_name/:id", to: 'properties#show'
  get "/proyectos/:property_name/:id", to: 'properties#show'
  get "/contact_us", to: 'contact#new'
  get "/about", to: 'welcome#about'
  get "/brokers", to: 'welcome#brokers'
  get "/:operation_type_name", to: 'properties#index', as: :properties, constraints: PropertyRouteConstraint
  get "/:operation_type_name/:property_type_name", to: 'properties#index', constraints: PropertyRouteConstraint
  get "/:operation_type_name/:property_type_name/:state_name", to: 'properties#index', constraints: PropertyRouteConstraint
  get "/:operation_type_name/:property_type_name/:state_name/:zone_name", to: 'properties#index', constraints: PropertyRouteConstraint

  post '/admin/update_styles', controller: 'admin/dashboard', action: 'update_styles'
end

app/views/shared/_consult_message.js.erb
<% if @consult_message[:success].present? %>
  $('.consult-messages').html("<div class='alert success'><i class='icon-check'></i><%= @consult_message[:success] %></div>");
<% elsif @consult_message[:error].present? %>
  $('.consult-messages').html("<div class='alert error'><%= @consult_message[:error] %></div>")
<% end %>

$('.consult-messages').show();
$('.consult-messages').delay(4000).fadeOut(400);
$('.consult-messages .alert').delay(4000).fadeOut(400);
$('.consult-messages').show();
$('.consult-messages .alert').show();

setTimeout(function(){
  $('.consult-messages').hide();
  $('.consult-messages .alert').hide();
  $(".consult-form textarea[name='question']").val('');

  if (/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) {
    enableScroll();
    $('.consult-modal').addClass('hidden');
  }
}, 4000);

app/views/shared/_flash_message.js.erb
<% if @flash_message[:success].present? %>
  $('#flash-messages').html("<div class='alert succes'><%= @flash_message[:success] %></div>");
<% elsif @flash_message[:error].present? %>
  $('#flash-messages').html("<div class='alert error'><%= @flash_message[:error] %></div>")
<% end %>
$('#flash-messages .alert').delay(5000).fadeOut(500)

app/views/shared/_footer_style_1.html.haml
%footer.main-footer
  .auto-container
    .row
      .footer-column.col-md-5.col-sm-5.col-xs-12
        = link_to '/', class: 'logo' do
          = image_tag 'logo.png', title: SITE_CONFIG['site_name'], alt: SITE_CONFIG['site_name']

      .footer-column.col-md-4.col-sm-4.col-xs-12
        %h2 Tags
        %ul
          %li
            = link_to 'Inmuebles', '/venta?utf8=%E2%9C%93&operation_type_name=venta&property_type_id%5B%5D=1&property_type_id%5B%5D=2&zone_id%5B%5D=D10&state_id=10'
          %li
            = link_to 'Propiedades en Alquiler', '/alquiler?utf8=%E2%9C%93&operation_type_name=alquiler&property_type_id%5B%5D=1&property_type_id%5B%5D=2&zone_id%5B%5D=D10&state_id=10'
          %li
            = link_to 'Propiedades en Venta', '/venta?property_type_id%5B%5D=2&property_type_id%5B%5D=1&state_id=10'
          %li
            = link_to 'Casas en Venta', '/venta?utf8=%E2%9C%93&operation_type_name=venta&property_type_id%5B%5D=1&zone_id%5B%5D=D10&state_id=10'

      .footer-column.social-column.col-md-3.col-sm-3.col-xs-12
        %h2 Social
        %ul
          %li
            = link_to 'https://www.facebook.com/ElObservadorUY/?ref=br_rs', target: '_blank' do
              .icon.fa.fa-facebook-f
              %span
                Facebook
          %li
            = link_to 'https://twitter.com/observadoruy?lang=en', target: '_blank' do
              .icon.fa.fa-twitter
              %span
                Twitter
          %li
            = link_to 'https://www.instagram.com/observadoruy/?hl=en', target: '_blank' do
              .icon.fa.fa-instagram
              %span
                Instagram
          %li
            = link_to 'https://www.youtube.com/user/ObservaUY', target: '_blank' do
              .icon.fa.fa-youtube
              %span
                Youtube
          %li
            = link_to 'https://play.spotify.com/user/observadoruy?play=true&utm_source=open.spotify.com&utm_medium=open&ref=wp', target: '_blank' do
              .icon.fa.fa-spotify
              %span
                Spotify
          %li
            = link_to 'https://www.pinterest.com/observadoruy/', target: '_blank' do
              .icon.fa.fa-pinterest
              %span
                Pinterest
          %li
            = link_to 'https://plus.google.com/u/0/+ElObservadorUru', target: '_blank' do
              .icon.fa.fa-google-plus
              %span
                Google +

    %hr

    .powered-by
      .text
        Powered by
      = image_tag 'infocasas.png', alt: ''

app/views/shared/_footer_style_2.html.haml
%footer.main-footer.style-2
  .auto-container
    .row
      .office-column.col-md-4.col-xs-12.c-left
        %h2 Contacto
        .line
        .info
          %a{ href: '#' }
            = image_tag 'map-marker.svg', alt: 'Ubicacion'
            Tiburcio Gómez 1330 Montevideo, Uruguay.
          %br
          %a{ href: 'https://api.whatsapp.com/send?phone=59894440224', target: '_blank' }
            = image_tag 'whatsapp.svg', alt: 'WhatsApp'
            (+598) 94 440 224
          %br
          %a{ href: 'mailto:mdeamestoy@zonabrokers.com' }
            = image_tag 'mailto.svg', alt: 'Email'
            mdeamestoy@zonabrokers.com
      .social-column.col-md-4.col-xs-12.c-center
        %h2 Seguinos
        .line
        .info
          %a{ href: 'https://www.facebook.com/zonabrokers' }
            = image_tag 'face.svg', alt: 'facebook'
          %br
          %a{ href: 'https://www.instagram.com/zonabrokers/' }
            = image_tag 'insta.svg', alt: 'Instagram'
          %br
          %a{ href: 'https://www.linkedin.com/company/zonabrokers' }
            = image_tag 'link.svg', alt: 'WhatsApp'
      .office-column.col-md-4.col-xs-12.c-footer
        .right
          = image_tag 'logo_f.svg', alt: 'Logo'
          .rfoter
            .powered-by
              %p Powered by
              = image_tag 'infocasas_g.svg', alt: 'Logo'
            .powered-by
              %p Socios
              = image_tag 'adiu.svg', alt: 'Logo'

app/views/shared/_footer_style_3.html.haml
%footer.main-footer.style-3
  .auto-container
    .row
      .links-column.col-md-4.col-sm-4.col-xs-12
        .links-box
          %h2 Links
          %ul
            %li
              = link_to 'Inicio', root_path
            %li
              = link_to 'Contacto', contact_us_path
        .social-box
          %h2 Social
          %ul
            %li
              = link_to 'https://www.facebook.com/inmobiliariakosak/', target: '_blank' do
                .icon.fa.fa-facebook-f
                %span
                  Facebook

            %li
              = link_to 'https://twitter.com/KosakUruguay', target: '_blank' do
                .icon.fa.fa-twitter
                %span
                  Twitter

      .office-column.col-md-4.col-sm-4.col-xs-12
        .office-box
          %h2
            Pocitos
          .info
            Bvar. España 2989
            %br/
            Tel.: 2707 1871*
            %br/
            kosak@kosak.com.uy
        .office-box
          %h2
            Carrasco / C. de la Costa
          .info
            Rostand 1551
            %br/
            Tel.: 2601 6242
            %br/
            carrasco@kosak.com.uy
      .office-column.col-md-4.col-sm-4.col-xs-12
        .office-box
          %h2
            Ciudad Vieja
          .info
            Alzaibar 1362
            %br/
            Tel.: 2916 9792
            %br/
            ciudadvieja@kosak.com.uy
        .office-box
          %h2
            Punta del Este
          .info
            Gorlero entre 28 y 29
            %br/
            Cel.: +598 97 122 319
            %br/
            punta@kosak.com.uy

    %hr

    .powered-by
      .text
        Powered by
      = image_tag 'infocasas.png', alt: ''

app/views/shared/_form_result.js.erb
$("form input").delay(3000).val('');
$("form textarea").delay(3000).val('');

<% if @result_message[:success].present? %>
  $('#submit-button').addClass('disabled')
  $('#submit-button').html('<%= @result_message[:success] %>');
<% elsif @result_message[:error].present? %>
  $('#flash-messages').html("<div class='alert error'><%= @result_message[:error] %></div>")
  $('#flash-messages .alert').delay(5000).fadeOut(500)
<% end %>

app/views/shared/_header_style_1.html.haml
%header.main-header
  = link_to '/', class: 'logo' do
    = image_tag 'logo.png', title: SITE_CONFIG['site_name'], alt: SITE_CONFIG['site_name']

  .powered-by
    .text
      Powered by
    = image_tag 'infocasas.png', alt: ''

  .right-container
    %a{ href: 'http://blog.infocasas.com.uy/', class: 'blog hidden-xs', target: '_blank' } BLOG
    %a{ href: 'http://www.infocasas.com.uy/registro', class: 'publish', target: '_blank' }
      %button.secondary{ class: "style-#{SITE_CONFIG['buttons_style']}" } PUBLICAR

app/views/shared/_header_style_2.html.haml
%header.main-header.style-2
  .container-head-main
    = link_to '/', class: 'logo' do
      = image_tag 'logo.svg', title: SITE_CONFIG['site_name'], alt: SITE_CONFIG['site_name']
    %button.visible-sm.visible-xs#menu-button{ class: "style-#{SITE_CONFIG['buttons_style']}" }
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    .right-container.visible-lg.visible-md.prevent-text-select#collapsable-menu
      = link_to 'PROPIEDADES', properties_path('venta')
      //= link_to 'ALQUILER', properties_path('alquiler')
      = link_to 'PROYECTOS', properties_path('proyectos') if SITE_CONFIG['display_projects']
      = link_to 'TERRENOS', properties_path('terrenos') if SITE_CONFIG['display_terrains']
      = link_to 'EMPRESA', about_path if SITE_CONFIG['display_about_page']
      = link_to 'BROKERS', brokers_path if SITE_CONFIG['display_brokers_page']
      = link_to 'BLOG', about_path if SITE_CONFIG['display_blog_page']
      = link_to 'CONTACTO', contact_us_path
  #whatsappBtn
    %a{:href => "https://api.whatsapp.com/send?phone=59894440224", :target => "_blank"}
      %button
        = image_tag 'whatsapp.png', alt: ''
      %span Escribinos

app/views/shared/_links-box.html.haml
- if links.present?
  %section.links_box
    .auto-container
      %h2.sec-title.centered
        = links[:title]
      .row
        - links[:sections].each do |section|
          - if section[:links].present?
            .col-lg-4.col-md-4.col-sm-6.col-xs-12
              %h3
                = section[:title]
              - section[:links].each do |link|
                = link_to ('(' + link['cantResults'].to_s + ') ' + link['texto']), "/#{link['href']}"

      %ul.links-carousel.owl-carousel.owl-theme
        - links[:sections].each do |section|
          - if section[:links].present?
            %li
              %h3
                = section[:title]
              - section[:links].each do |link|
                = link_to ('(' + link['cantResults'].to_s + ') ' + link['texto']), "/#{link['href']}"

app/views/shared/_loader.html.haml
- transparent = false if local_assigns[:transparent].nil?
.loader{ class: [('hidden' if hidden), ('fullscreen' if fullscreen), ('transparent' if transparent)]  }
  .spinner
    .bounce1
    .bounce2
    .bounce3

app/views/shared/_newsletter.html.haml
%section.newsletter-section
  .outer-box
    .shadow
    %h2.sec-title.centered
      Recibí propiedades en tu email
    .newsletter-style-one
      = form_tag newsletter_subscribe_path, method: 'post', remote: true do
        .form-group
          %input{ name: 'email', placeholder: 'Escribe tu Email', required: '', type: 'email', value: '' }/
          %button.primary{ class: "style-#{SITE_CONFIG['buttons_style']}", type: 'submit', id: 'submit-button' } Suscribirme

app/views/shared/_sponsors.html.haml
%section.sponsors-section
  .auto-container
    / Heading
    .sec-title.centered
      %h2 Our Partners
    %ul.sponsors-carousel.owl-theme.owl-carousel
      %li
        %figure.image
          %a{:href => "#"}
            = image_tag 'sponsors/1.png', alt: ''
      %li
        %figure.image
          %a{:href => "#"}
            = image_tag 'sponsors/2.png', alt: ''
      %li
        %figure.image
          %a{:href => "#"}
            = image_tag 'sponsors/3.png', alt: ''
      %li
        %figure.image
          %a{:href => "#"}
            = image_tag 'sponsors/4.png', alt: ''
      %li
        %figure.image
          %a{:href => "#"}
            = image_tag 'sponsors/1.png', alt: ''
      %li
        %figure.image
          %a{:href => "#"}
            = image_tag 'sponsors/2.png', alt: ''
      %li
        %figure.image
          %a{:href => "#"}
            = image_tag 'sponsors/3.png', alt: ''
      %li
        %figure.image
          %a{:href => "#"}
            = image_tag 'sponsors/4.png', alt: ''