config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'welcome#index'
  post 'newsletter_subscribe', to: 'welcome#newsletter_subscribe'

  resources :contact, only: [:new, :create]
  resources :posts, only: [:index, :show]
  resources :properties, only: [:show] do
    get :highlighted, on: :collection
    get :reference_search, on: :collection
    get :images, on: :member
    post :consult, on: :member
    post :consult_express, on: :member
  end

  get "/propiedades/:property_name/:id", to: 'properties#show'
  get "/proyectos/:property_name/:id", to: 'properties#show'
  get "/contact_us", to: 'contact#new'
  get "/about", to: 'welcome#about'
  get "/brokers", to: 'welcome#brokers'
  get "/:operation_type_name", to: 'properties#index', as: :properties, constraints: PropertyRouteConstraint
  get "/:operation_type_name/:property_type_name", to: 'properties#index', constraints: PropertyRouteConstraint
  get "/:operation_type_name/:property_type_name/:state_name", to: 'properties#index', constraints: PropertyRouteConstraint
  get "/:operation_type_name/:property_type_name/:state_name/:zone_name", to: 'properties#index', constraints: PropertyRouteConstraint

  post '/admin/update_styles', controller: 'admin/dashboard', action: 'update_styles'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  include FilterHelper
  include ParamsConverter

  def index
    requests_service = RequestsService.new(request.user_agent)
    @banner = requests_service.home_banner
    @home_banners = requests_service.home_banners
    operation_type = params[:IDoperaciones] || 1
    @operation_type_param = operation_types.find { |obj| obj[:id] == operation_type.to_s }
    @properties = requests_service.highlighted_properties(operation_type)

    if SITE_CONFIG['display_links_box']
      links = requests_service.landing_links
      if links.present?
        @link_params = {
          title: 'Búsquedas destacadas',
          sections: [
            { title: 'ALQUILER', links: links['Alquileres'] },
            { title: 'VENTA', links: links['Ventas'] },
            { title: 'ALOJAMIENTOS', links: links['Alojamientos'] }
          ]
        }

        @link_params[:sections].try(:each) do |section|
          section[:links].try(:each) do |link|
            params = link['paramsBusqueda']
            link['href'] = params_to_url(params)
          end
        end
      end
    end
  end

  def newsletter_subscribe
    requests_service = RequestsService.new(request.user_agent)
    @result_message = requests_service.newsletter_subscribe(params[:email])
    render partial: 'shared/form_result'
  end

  def about
    if SITE_CONFIG['display_about_page']
      render 'welcome/about_style_' + SITE_CONFIG['about_page_style']
    else
      redirect_to root_url
    end
  end

  def brokers
    if SITE_CONFIG['display_brokers_page']
      render 'welcome/brokers_style_' + SITE_CONFIG['brokers_page_style']
    else
      redirect_to root_url
    end
  end

end

app/views/welcome/_banner-square.html.haml
%h3
  BUSCAR MI PROPIEDAD
.form-group.col-md-6.col-sm-6.col-xs-6#operation_type_column
  = select_tag "operation_type_name", options_for_select(search_operation_types.map { |obj| [obj[:name], name_to_param(obj[:name])] }), multiple: false, class: 'multiple', id: 'operation_type_name_select'
.form-group.col-md-6.col-sm-6.col-xs-6#property_type_column
  = select_tag "property_type_id", options_for_select(property_types.map { |obj| [obj[:name], obj[:id]] }), multiple: true, class: 'multiple', id: 'property_type_id_select', required: ''
.form-group.col-md-12.col-sm-12.col-xs-12#property_location_column
  = select_tag "zone_id", options_for_select(zones.map { |obj| [obj[:name].present? ? "#{obj[:state]} - #{obj[:name]}" : "#{obj[:state]} (Departamento)", obj[:id]] }), multiple: true, class: 'multiple', required: ''
.form-group.col-md-12.col-sm-12.col-xs-12
  %button.submit.truncated.primary{ class: "style-#{SITE_CONFIG['buttons_style']}", type: "submit" } Buscar

app/views/welcome/_banner-wide.html.haml
.form-group.col-md-2.col-sm-2.col-xs-6#operation_type_column
  = select_tag "operation_type_name", options_for_select(search_operation_types.map { |obj| [obj[:name], name_to_param(obj[:name])] }), multiple: false, class: 'multiple', id: 'operation_type_name_select'
.form-group.col-md-3.col-sm-3.col-xs-6#property_type_column
  = select_tag "property_type_id", options_for_select(property_types.map { |obj| [obj[:name], obj[:id]] }), multiple: true, class: 'multiple', id: 'property_type_id_select', required: ''
.form-group.col-md-6.col-sm-6.col-xs-12#property_location_column
  = select_tag "zone_id", options_for_select(zones.map { |obj| [obj[:name].present? ? "#{obj[:state]} - #{obj[:name]}" : "#{obj[:state]} (Departamento)", obj[:id]] }), multiple: true, class: 'multiple', required: ''
.form-group.col-md-1.col-sm-1.col-xs-12
  %button.submit.truncated.primary{ class: "style-#{SITE_CONFIG['buttons_style']}", type: "submit" } Buscar

app/views/welcome/_banner.html.haml
%section.home-banner{ class: "style-#{SITE_CONFIG['home_banner_style']}" }
  .gradient
  .form-container
    %h1 #{SITE_CONFIG['home_title'].html_safe}
    .banner-form-box
      .container
        .row
          = form_tag '/', method: 'get', class: 'properties-search' do
            - if SITE_CONFIG['home_banner_style'] == '4'
              = render partial: 'welcome/banner-square'
            - else
              = render partial: 'welcome/banner-wide'
            .hidden
              = select_tag "state_id", options_for_select(states.map { |obj| ["#{obj[:name]}", obj[:id]] })
        - if SITE_CONFIG['home_banner_style'] != '5'
          .row
            .search-by-reference.col-md-6.col-sm-6.col-xs-8
              %i.icon-plus-circled
              Buscar por referencia
            -# .powered-by.col-md-6.col-sm-6.col-xs-4
            -#   .text
            -#     Powered by
            -#   = image_tag 'infocasas.png', alt: ''
        .row
          = form_tag reference_search_properties_path, method: 'get', class: 'reference-search hidden' do
            - if SITE_CONFIG['home_banner_style'] == '5'
              .text
                Buscar por referencia
            %input{ name: 'ref', placeholder: 'Ref. 12345', required: '', type: 'text', value: '', class: 'reference-search-input' }
            %button.primary{ class: "style-#{SITE_CONFIG['buttons_style']}", type: 'submit'}
              = fa_icon "chevron-right"
    .logo
      .powered-by.col-md-8.col-sm-6.col-xs-12
        .text
          Powered by
        = image_tag 'infocasasb.svg', alt: ''

  - if SITE_CONFIG['display_continue_search']
    .continue-search-container
      = link_to '', class: 'continue-search hidden' do
        %button.primary.big{ class: "style-#{SITE_CONFIG['buttons_style']}" }
          Continuar con mi última búsqueda

app/views/welcome/_highlighted-properties.html.haml
%section.property-listing{ class: "style-#{SITE_CONFIG['home_titles_style']}" }
  %h2.sec-title.centered
    Propiedades destacadas
  .auto-container
    / Filter
    .filters.property-listing-tabs
      %ul.filter-tabs.filter-btns.clearfix
        %li.filter{ "data-value": 0, class: ('active' if  selected == '0')}
          TODAS
        %li.filter{ "data-value": 1, class: ('active' if  selected == '1')}
          VENTA
        %li.filter{ "data-value": 2, class: ('active' if  selected == '2')}
          ALQUILER
    .filter-list.row.clearfix
      / Default Property Box
      = render partial: "shared/loader", locals: { fullscreen: false, hidden: true }
      - @properties.each do |property|
        = render partial: 'properties/property_style_' + SITE_CONFIG['property_box_style'], locals: { property: property }

app/views/welcome/_highlights.html.haml
%section.ads-highlights{ class: "style-#{SITE_CONFIG['home_titles_style']}" }
  %h2.sec-title.centered Destacados #{SITE_CONFIG['site_name']}
  .banner-container.banners-carousel
    .banner.square#div-gpt-ad-1503513918839-2
    .banner.square#div-gpt-ad-1503513918839-3
    .banner.square#div-gpt-ad-1503513918839-4

app/views/welcome/about_style_1.html.haml
- if SITE_CONFIG['set_og_tags']
  - set_meta_tags og: { title: 'Nosotros', url: request.original_url, image: 'logo.png' }
- title 'Nosotros'

.page-content
  %section.about-container
    .auto-container
      .info-container
        %h1
          NOSOTROS
        .text
          Somos una empresa familiar apasionada por lo que hacemos. Nuestro sello y energías están enfocadas en brindar un servicio personalizado durante toda la gestión, tanto en la búsqueda como en la venta, sintiendo que más que una propiedad, gestionamos un HOGAR.
        .text
          Nos gusta que nuestros clientes estén tranquilos mientras nosotros trabajamos para ellos.

app/views/welcome/about_style_2.html.haml
- if SITE_CONFIG['set_og_tags']
  - set_meta_tags og: { title: 'Empresa', url: request.original_url, image: 'aboutPage/about-page.jpg' }
- title 'Empresa'

.page-content
  %section.about-container.style-2
    .image-container
    .description.container
      .row
        .col-12
          %h2 Quienes somos
          %p Zona Brokers nace en el rubro inmobiliario para ofrecer un servicio actual y personalizado a todos nuestros clientes a través de una nueva generación de profesionales que entienden las necesidades de un mercado en constante cambio.
          %p Contamos con un departamento legal que brinda asesoría con escribanos, contadores y abogados, que se encargarán de todos los servicios referentes a la propiedad. Colaboramos con todos los colegas del sector compartiendo la comercialización de las propiedades para realizarlo en el menor tiempo, con la mayor cantidad de ofertas y logrando el mejor precio que el mercado está dispuesto a ofrecer.
          %p Esto nos da la posibilidad de potenciar nuestros recursos junto al resto de las inmobiliarias, incorporando nuevas fuerzas de ventas y bajando los tiempos en cada transacción.
          %p Para los inversores que confían en nuestro trabajo contamos con amplio catálogo de propiedades dentro y fuera de Montevideo, con unidades en pozo, en construcción y de entrega inmediata.
          %h5 Encontramos una oportunidad hecha a tu medida.
  %section.about-containerb
    .container
      .row
        .col-12
          %h2 Algunos de nuestros servicios exclusivos:
          %h5 ¡Lográ mejores resultados en menos tiempo y con el mayor profesionalismo!
        .col-lg-4.col-xs-12
          = image_tag 'aboutPage/fotografia.svg', class: 'foto image', alt: ''
          .line
          %p
            %span Fotografía inmobiliaria
            %br
            Fotos y videos profesionales para resaltar la potencialidad de tu propiedad.
        .col-lg-4.col-xs-12
          = image_tag 'aboutPage/marketing.svg', class: 'marketing image', alt: ''
          .line
          %p
            %span Marketing digital
            %br
            Nos valemos de nuevas tecnologías para que tu propiedad esté donde está el público, con anuncios en redes sociales y portales digitales.
        .col-lg-4.col-xs-12
          = image_tag 'aboutPage/publicaciones.svg', class: 'publicaciones image', alt: ''
          .line
          %p
            %span Publicaciones específicas
            %br
            Realizaremos publicaciones estratégicas y avisos destacados en distintos medios para alcanzar a potenciales clientes.
        .col-lg-4.col-xs-12
          = image_tag 'aboutPage/reportes.svg', class: 'reportes image', alt: ''
          .line
          %p
            %span Reportes
            %br
            Nuestros clientes recibirán de forma quincenal un informe con el seguimiento de su propiedad.
        .col-lg-4.col-xs-12
          = image_tag 'aboutPage/tasasiones.svg', class: 'tasasiones image', alt: ''
          .line
          %p
            %span Tasación
            %br
            Tasación personalizada de tu propiedad a valor de mercado.
        .col-lg-4.col-xs-12
          = image_tag 'aboutPage/eventos.svg', class: 'eventos image', alt: ''
          .line
          %p
            %span Eventos
            %br
            Concurrimos a eventos inmobiliarios nacionales e internacionales.
  %section.about-containerc
    .container
      .row
        .col-12
          %h2 Conocé a nuestro equipo:
        .col-lg-4.col-xs-12.equipo
          = image_tag 'aboutPage/agentes/maria.png', class: 'agente', alt: ''
          %h5
            %span Ma. Noel Deamestoy
          %h5 Directora
          .line
          %p +598 94 440 224
          %p.correo mdeamestoy@zonabrokers.com
          %a.primary.propiedad{:href => "https://zonabrokers.com/propiedades/?broker_id=17497"}
            Ver propiedades
        .col-lg-4.col-xs-12.equipo
          = image_tag 'aboutPage/agentes/daniel.png', class: 'agente', alt: ''
          %h5
            %span Daniel Vilar
          %h5 Agente inmobiliario
          .line
          %p +598 96 171 386
          %p.correo dvilar@zonabrokers.com
          %a.primary.propiedad{:href => "https://zonabrokers.com/propiedades/?broker_id=17363"}
            Ver propiedades
        .col-lg-4.col-xs-12.equipo
          = image_tag 'aboutPage/agentes/camila.png', class: 'agente', alt: ''
          %h5
            %span Camila Páez
          %h5 Agente inmobiliario
          .line
          %p +598 97 792 360
          %p.correo cpaez@zonabrokers.com
          %a.primary.propiedad{:href => "https://zonabrokers.com/propiedades/?broker_id=17364"}
            Ver propiedades
        .col-lg-4.col-xs-12.equipo
          = image_tag 'aboutPage/agentes/joaquin.png', class: 'agente', alt: ''
          %h5
            %span Joaquín Navarro
          %h5 Agente inmobiliario
          .line
          %p +598 95 157 268
          %p.correo jnavarro@zonabrokers.com
          %a.primary.propiedad{:href => "https://zonabrokers.com/propiedades/?broker_id=17457"}
            Ver propiedades
        .col-lg-4.col-xs-12.equipo
          = image_tag 'aboutPage/agentes/gabriel.png', class: 'agente', alt: ''
          %h5
            %span Gabriel Montero
          %h5 Agente inmobiliario
          .line
          %p +598 93 985 102
          %p.correo gmontero@zonabrokers.com
          %a.primary.propiedad{:href => "https://zonabrokers.com/propiedades/?broker_id=17396"}
            Ver propiedades
        .col-lg-4.col-xs-12.equipo
          = image_tag 'aboutPage/agentes/fabian.jpg', class: 'agente', alt: ''
          %h5
            %span Fabian Fagundez
          %h5 Agente inmobiliario
          .line
          %p +598 96 026 917
          %p.correo ffagundez@zonabrokers.com
          %a.primary.propiedad{:href => "https://zonabrokers.com/propiedades/?broker_id=17444"}
            Ver propiedades

app/views/welcome/brokers_style_1.html.haml
- if SITE_CONFIG['set_og_tags']
  - set_meta_tags og: { title: 'Brokers', url: request.original_url, image: 'brokersPage/brokers-page.jpg' }
  - title 'Brokers'

.page-content
  %section.brokers-container.style-1
    .image-container
    .description.container
      .row
        .col-12
          %h2 ¿Por qué sumarte a Zona Brokers?
          %h5 Te proponemos sumarte al dinámico mundo del Real Estate, a través de un equipo que te brindará todo el respaldo, conocimiento y herramientas para que lideres tu propio emprendimiento.
        .col-lg-4.col-xs-12.motivo
          = image_tag 'brokersPage/respaldo.svg', class: 'image', alt: ''
          %p
            %span Respaldo
            %br
            Podrás sumarte a una empresa especializada en Real Estate con trayectoria de experiencia y un grupo consolidado de profesionales que te respalda.
        .col-lg-4.col-xs-12.motivo
          = image_tag 'brokersPage/honorarios.svg', class: 'image', alt: ''
          %p
            %span Honorarios
            %br
            Obtendrás honorarios atractivos y reglas claras en todo momento.
        .col-lg-4.col-xs-12.motivo
          = image_tag 'brokersPage/crecimiento.svg', class: 'image', alt: ''
          %p
            %span Crecimiento
            %br
            Te ofrecemos herramientas para tu desarrollo con inversión en marketing, espacio en plataforma tecnológica y visibilidad en medios.
        .col-lg-4.col-xs-12.motivo
          = image_tag 'brokersPage/capacitacion.svg', class: 'image', alt: ''
          %p
            %span Capacitación
            %br
            Fomentamos la formación de nuestros Brokers con jornadas de charlas y capacitaciones.
        .col-lg-4.col-xs-12.motivo
          = image_tag 'brokersPage/independencia.svg', class: 'image', alt: ''
          %p
            %span Independecia
            %br
            Tendrás libertad horaria y autonomía para organizar tu negocio de acuerdo a tus necesidades.
  %section.brokers-container
    .perfilBroker
      .brokerCol
        = image_tag 'brokersPage/staff.jpg', alt: 'img'
      .brokerCol.bg
        .innerColBroker
          %p.bigTitle Unite a nuestro staff
          %ul
            %li
              %i.icon-check
              %p Si deseás crecer profesional y económicamente con excelentes condiciones laborales.
            %li
              %i.icon-check
              %p Si tenés vocación por el servicio, acompañando y dando seguimiento a tus clientes.
            %li
              %i.icon-check
              %p Si sos una persona proactiva, con buenas habilidades de comunicación y voluntad.
            %li
              %i.icon-check
              %p Si disfrutás el mundo del Real Estate, hacer negocios y obtener buenos honorarios.
    .contact-container
      %h2 ¿Querés formar parte de Zona Brokers?
      %p.preContact Escribinos para tener una entrevista.
      = form_tag contact_index_path, method: 'post', id: 'contact-form', remote: true do
        .contact-form
          .form-group.col-md-4.col-sm-4.col-xs-12
            %input{ name: 'name', placeholder: 'Nombre*', required: true, type: 'text', value: '' }
          .form-group.col-md-4.col-sm-4.col-xs-12
            %input{ class: 'contact-email', name: 'email', placeholder: 'Email*', required: true, type: 'email', value: '' }
          .form-group.col-md-4.col-sm-4.col-xs-12
            %input{ name: 'phone', placeholder: 'Teléfono', required: false }
          %button.primary.big{ class: "style-#{SITE_CONFIG['buttons_style']}", type: 'submit', id: 'submit-button' } ¡Enviar Solicitud!

app/views/welcome/index.html.haml
- if SITE_CONFIG['set_og_tags']
  - set_meta_tags og: { title: SITE_CONFIG['site_title'], url: request.original_url, image: 'banners/Banner-Header-Home.jpg' }

- title SITE_CONFIG['site_title']

= render partial: 'banner'

- if SITE_CONFIG['display_ads_banners']
  = render partial: 'highlights'

- if SITE_CONFIG['display_ads_banners']
  = render partial: 'highlights'

= render partial: 'highlighted-properties', locals: { selected: '1' }

- if SITE_CONFIG['display_ads_banners']
  .banner-container
    .banner.rectangular-long#div-gpt-ad-1503513918839-1

- if SITE_CONFIG['display_home_image']
  = image_tag 'city.jpg', alt: '', class: 'section-divider'

- if SITE_CONFIG['display_links_box']
  = render partial: 'shared/links-box', locals: { links: @link_params }

- if SITE_CONFIG['display_home_carousel']
  .carousel-highlights-container
    .images-carousel.owl-theme.owl-carousel
      - @home_banners.each do |banner|
        %a{ href: "#{banner['link']}", target: "#{banner['target']}" }
          .text-overlay
            = banner['title']
          .image
            = image_tag banner['file']

- if SITE_CONFIG['display_newsletter']
  = render partial: 'shared/newsletter'

app/views/welcome/zona_style_1.html.haml
- if SITE_CONFIG['set_og_tags']
  - set_meta_tags og: { title: 'Vision', url: request.original_url, image: 'zonaPage/zona-page.jpg' }
- title 'Brokers'

.page-content
  %section.zona-container.style-1
    .image-container
    .description.container
      .row
        .col-12
          %h2 ¿Por qué sumarte a Zona Brokers?
          %h5 Te proponemos sumarte al dinámico mundo del Real Estate, a través de un equipo que te brindará todo el respaldo, conocimiento y herramientas para que lideres tu propio emprendimiento.
        .col-lg-4.col-xs-12
          = image_tag 'zonaPage/respaldo.svg', class: 'image', alt: ''
          %p
            %span Respaldo
            %br
            Podrás sumarte a una empresa especializada en Real Estate con trayectoria de experiencia y un grupo consolidado de profesionales que te respalda.
        .col-lg-4.col-xs-12
          = image_tag 'zonaPage/honorarios.svg', class: 'image', alt: ''
          %p
            %span Honorarios
            %br
            Obtendrás honorarios atractivos y reglas claras en todo momento.
        .col-lg-4.col-xs-12
          = image_tag 'zonaPage/crecimiento.svg', class: 'image', alt: ''
          %p
            %span Crecimiento
            %br
            Te ofrecemos herramientas para tu desarrollo con inversión en marketing, espacio en plataforma tecnológica y visibilidad en medios.
        .col-lg-4.col-xs-12
          = image_tag 'zonaPage/capacitacion.svg', class: 'image', alt: ''
          %p
            %span Capacitación
            %br
            Fomentamos la formación de nuestros Brokers con jornadas de charlas y capacitaciones.
        .col-lg-4.col-xs-12
          = image_tag 'zonaPage/independencia.svg', class: 'image', alt: ''
          %p
            %span Independecia
            %br
            Tendrás libertad horaria y autonomía para organizar tu negocio de acuerdo a tus necesidades.
  %section.zona-containerc
    .container
      .row
        .col-lg-6.col-xs-12.equipo
          %h2 Unite a nuestro staff
          %ul
            %li Si deseás crecer profesional y económicamente con excelentes condiciones laborales.
            %li Si tenés vocación por el servicio, acompañando y dando seguimiento a tus clientes.
            %li Si sos una persona proactiva, con buenas habilidades de comunicación y voluntad.
            %li Si disfrutás el mundo del Real Estate, hacer negocios y obtener buenos honorarios.