config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'welcome#index'
  post 'newsletter_subscribe', to: 'welcome#newsletter_subscribe'

  resources :contact, only: [:new, :create]
  resources :posts, only: [:index, :show]
  resources :properties, only: [:show] do
    get :highlighted, on: :collection
    get :reference_search, on: :collection
    get :images, on: :member
    post :consult, on: :member
    post :consult_express, on: :member
  end

  get "/propiedades/:property_name/:id", to: 'properties#show'
  get "/proyectos/:property_name/:id", to: 'properties#show'
  get "/contact_us", to: 'contact#new'
  get "/about", to: 'welcome#about'
  get "/brokers", to: 'welcome#brokers'
  get "/:operation_type_name", to: 'properties#index', as: :properties, constraints: PropertyRouteConstraint
  get "/:operation_type_name/:property_type_name", to: 'properties#index', constraints: PropertyRouteConstraint
  get "/:operation_type_name/:property_type_name/:state_name", to: 'properties#index', constraints: PropertyRouteConstraint
  get "/:operation_type_name/:property_type_name/:state_name/:zone_name", to: 'properties#index', constraints: PropertyRouteConstraint

  post '/admin/update_styles', controller: 'admin/dashboard', action: 'update_styles'
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :create_posts_service

  def index
    request_params = {}
    request_params[:pageToken] = params[:page_token] if params[:page_token].present?
    @blog = @posts_service.posts(request_params)
    @posts = @blog['items']
  end

  def show
    @post = @posts_service.post(params[:id])
  end

  private

  def create_posts_service
    @posts_service = PostsService.new
  end
end

app/views/posts/_post.html.haml
.post-box.news-style-one.col-lg-4.col-md-6.col-sm-6.col-xs-12
  .inner-box
    %figure.image-box
      = link_to post_path(id: post['id']), target: '_blank' do
        - if post['images'].present?
          = image_tag post['images'].first['url'], alt: ''
        - else
          = image_tag 'newsletter.jpg', alt: ''
    .lower-content
      .post-meta
        %ul
          %li
            = l(post['updated'].to_date, format: "%d %B, %Y").titleize
            por
            = post['author']['displayName']
      %h3.truncated
        = link_to post_path(id: post['id']), target: '_blank' do
          = post['title']
      .text.truncated-3
        - post['content'].gsub!(/[\n]+/,' ')
        - post['content'].gsub!(/(<div.*?>)+/,'')
        - post['content'].gsub!(/(<\/div>)+/,'')
        - post['content'].gsub!(/(<(a|b|li|ul).*?>)+/,'')
        - post['content'].gsub!(/(<\/(a|b|li|ul)>)+/,'')
        - post['content'].gsub!(/(&nbsp;)+/,' ')
        - post['content'].gsub!(/<span.*?>+/,'')
        - post['content'].gsub!(/<\/span>+/,'')
        = post['content'].html_safe

app/views/posts/index.html.haml
- title 'Noticias'

.page-content
  %section.blog-header
    .gradient
    %h1 BLOG

  %section.blog
    .auto-container
      .row.clearfix
        .posts-container
          - @posts.each do |post|
            = render partial: 'posts/post', locals: { post: post }
        - if @blog['nextPageToken'].present?
          .load-more-container
            = image_tag "ajax-loader.gif", class: 'loading-gif hidden'
            %button.primary.big.load-more{ class: "style-#{SITE_CONFIG['buttons_style']}" }
              = link_to "Cargar más", posts_path(page_token: @blog['nextPageToken']), remote: true

app/views/posts/index.js.erb
<% @posts.each do |post| %>
  $('.posts-container').append("<%= escape_javascript(render partial: 'posts/post', locals: { post: post }) %>")
<% end %>
$('.loading-gif').addClass('hidden');
<% if @blog['nextPageToken'].present? %>
  $('.load-more').removeClass('hidden');
<% end %>

app/views/posts/show.html.haml
- set_meta_tags og: { title: @post['title'], url: request.original_url, image: @post['images'].present? ? @post['images'].first['url'] : '' }

%section.blog-header
  .gradient
  %h1 BLOG

%section.blog-details
  .auto-container
    .row.clearfix
      .news-style-one
        .inner-box
          .lower-content
            = link_to posts_path, class: 'return-button' do
              = fa_icon 'arrow-left'
              VOLVER
            - if @post['updated'].present?
              .post-meta
                = l(@post['updated'].to_date, format: "%d %B, %Y").titleize
                por
                = @post['author']['displayName']
            %h3
              = title @post['title']
            .text
              = @post['content'].html_safe
        .post-options
          .clearfix
            .share-options.clearfix
              %strong Compartilo en:

              %ul.social-links-one
                %li
                  = link_to "https://www.facebook.com/sharer/sharer.php?u=#{@post['url']}", target: '_blank' do
                    %span.fa.fa-facebook-f
                %li
                  = link_to "https://twitter.com/home?status=#{@post['url']}", target: '_blank' do
                    %span.fa.fa-twitter
                %li.visible-mobile.hidden
                  = link_to "whatsapp://send?text=#{@post['url']}", 'data-action': 'share/whatsapp/share' do
                    %span.fa.fa-whatsapp

      - if @post['replies']['totalItems'].to_i > 0
        .comments-area
          .group-title
            %h2
              = @post['replies']['totalItems']
              Comentarios
          - if @post['replies']['items'].present?
            .comment-box
              - @post['replies']['items'].each do |comment|
                - if comment['inReplyTo'].blank?
                  .comment
                    .comment-inner
                      .author-thumb
                        = image_tag comment['author']['image']['url'], alt: ''
                      .comment-content
                        .text
                          = comment['content']
                        .comment-info.clearfix
                          %strong
                            = comment['author']['displayName']
                          .time
                            = l(comment['updated'].to_date, format: "%d %B, %Y").titleize

                  - @post['replies']['items'].each do |reply|
                    - if reply['inReplyTo'].present? && reply['inReplyTo']['id'] == comment['id']
                      .comment.reply-comment
                        .comment-inner
                          .author-thumb
                            = image_tag reply['author']['image']['url'], alt: ''
                          .comment-content
                            .text
                              = reply['content']
                            .comment-info.clearfix
                              %strong
                                = reply['author']['displayName']
                              .time
                                = l(reply['updated'].to_date, format: "%d %B, %Y").titleize